### ISSUE TITLE
Add fix for broken links, new entries

### ISSUE THREAD

**Issue by coreystone** [privacy-tech-lab/gpc-ccpa-metrics#2]
Hello! Your projects have recently caught my attention and this is one I believe I can help contribute to.  

I've reviewed most of the companies in the existing Google spreadsheet and updated **around 70** broken or relocated links and also updated their dates. I also added about 5 new companies. 

Here is the resulting file: [**ccpa_metrics.csv**](https://github.com/privacy-tech-lab/ccpa-metrics/files/10917716/ccpa_metrics.csv)

I did not update specific metric values- just the links and dates. If there are plans to update this project then this is something I would consider helping with in the future as well.

For context, I am working on a [related project ("Privacy Policy Directory")](https://github.com/coreystone/privacy-policy-directory-data) that aggregates company privacy policies and identifies interesting data points about them, *including* a link to their CCPA metric pages. I've partly automated this process and am continuing to add new entries to the directory, which includes CCPA metrics links. The data obtained from this directory could be useful/applied to this project. I appreciate the work that your team is doing and wanted to let you know that I am willing to help out where I can. Please let me know if there is something else I could do to help or how I could make my project more useful for your team.

**Comment by SebastianZimmeck** [comment]
Thanks so much, @coreystone! I added a reference to your contribution in the [readme](https://github.com/privacy-tech-lab/ccpa-metrics#readme). At the moment, I do not have the time to review and update the Google Sheet, but I will get to it eventually ... . :)
